/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StudioLoginRouteImport } from './routes/studio-login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as OurWorkIndexRouteImport } from './routes/our-work.index'
import { Route as OurWorkSlugRouteImport } from './routes/our-work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioLoginRoute = StudioLoginRouteImport.update({
  id: '/studio-login',
  path: '/studio-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OurWorkIndexRoute = OurWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OurWorkRoute,
} as any)
const OurWorkSlugRoute = OurWorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OurWorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/our-work': typeof OurWorkRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/studio-login': typeof StudioLoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/our-work/': typeof OurWorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/studio-login': typeof StudioLoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/our-work': typeof OurWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/our-work': typeof OurWorkRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/studio-login': typeof StudioLoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/our-work/': typeof OurWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/our-work'
    | '/reviews'
    | '/services'
    | '/studio-login'
    | '/admin'
    | '/our-work/$slug'
    | '/our-work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/reviews'
    | '/services'
    | '/studio-login'
    | '/admin'
    | '/our-work/$slug'
    | '/our-work'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/our-work'
    | '/reviews'
    | '/services'
    | '/studio-login'
    | '/_authenticated/admin'
    | '/our-work/$slug'
    | '/our-work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  OurWorkRoute: typeof OurWorkRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  StudioLoginRoute: typeof StudioLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-login': {
      id: '/studio-login'
      path: '/studio-login'
      fullPath: '/studio-login'
      preLoaderRoute: typeof StudioLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/our-work/': {
      id: '/our-work/'
      path: '/'
      fullPath: '/our-work/'
      preLoaderRoute: typeof OurWorkIndexRouteImport
      parentRoute: typeof OurWorkRoute
    }
    '/our-work/$slug': {
      id: '/our-work/$slug'
      path: '/$slug'
      fullPath: '/our-work/$slug'
      preLoaderRoute: typeof OurWorkSlugRouteImport
      parentRoute: typeof OurWorkRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OurWorkRouteChildren {
  OurWorkSlugRoute: typeof OurWorkSlugRoute
  OurWorkIndexRoute: typeof OurWorkIndexRoute
}

const OurWorkRouteChildren: OurWorkRouteChildren = {
  OurWorkSlugRoute: OurWorkSlugRoute,
  OurWorkIndexRoute: OurWorkIndexRoute,
}

const OurWorkRouteWithChildren =
  OurWorkRoute._addFileChildren(OurWorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  OurWorkRoute: OurWorkRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  StudioLoginRoute: StudioLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
